//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAdmin.Models.Jira
{
    using System;
    using System.Collections.Generic;
    
    public partial class cwd_user
    {
        public decimal ID { get; set; }
        public Nullable<decimal> directory_id { get; set; }
        public string user_name { get; set; }
        public string lower_user_name { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string first_name { get; set; }
        public string lower_first_name { get; set; }
        public string last_name { get; set; }
        public string lower_last_name { get; set; }
        public string display_name { get; set; }
        public string lower_display_name { get; set; }
        public string email_address { get; set; }
        public string lower_email_address { get; set; }
        public string CREDENTIAL { get; set; }
        public Nullable<int> deleted_externally { get; set; }
        public string EXTERNAL_ID { get; set; }
    }
}
