//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAdmin.Models.Jira
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JiraDbContext : DbContext
    {
        public JiraDbContext()
            : base("name=JiraDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
           // modelBuilder.Configurations.Add(new app_user());
        }
    
        public virtual DbSet<app_user> app_user { get; set; }
        public virtual DbSet<cwd_user> cwd_user { get; set; }
        public virtual DbSet<jiraissue> jiraissues { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<worklog> worklogs { get; set; }
    }
}
