//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAdmin.Models.Jira
{
    using System;
    using System.Collections.Generic;
    
    public partial class jiraissue
    {
        public decimal ID { get; set; }
        public string pkey { get; set; }
        public Nullable<decimal> issuenum { get; set; }
        public Nullable<decimal> PROJECT { get; set; }
        public string REPORTER { get; set; }
        public string ASSIGNEE { get; set; }
        public string CREATOR { get; set; }
        public string issuetype { get; set; }
        public string SUMMARY { get; set; }
        public string DESCRIPTION { get; set; }
        public string ENVIRONMENT { get; set; }
        public string PRIORITY { get; set; }
        public string RESOLUTION { get; set; }
        public string issuestatus { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<System.DateTime> RESOLUTIONDATE { get; set; }
        public Nullable<decimal> VOTES { get; set; }
        public Nullable<decimal> WATCHES { get; set; }
        public Nullable<decimal> TIMEORIGINALESTIMATE { get; set; }
        public Nullable<decimal> TIMEESTIMATE { get; set; }
        public Nullable<decimal> TIMESPENT { get; set; }
        public Nullable<decimal> WORKFLOW_ID { get; set; }
        public Nullable<decimal> SECURITY { get; set; }
        public Nullable<decimal> FIXFOR { get; set; }
        public Nullable<decimal> COMPONENT { get; set; }
    }
}
