//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAdmin.Models.Jira
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public decimal ID { get; set; }
        public string pname { get; set; }
        public string URL { get; set; }
        public string LEAD { get; set; }
        public string DESCRIPTION { get; set; }
        public string pkey { get; set; }
        public Nullable<decimal> pcounter { get; set; }
        public Nullable<decimal> ASSIGNEETYPE { get; set; }
        public Nullable<decimal> AVATAR { get; set; }
        public string ORIGINALKEY { get; set; }
    }
}
