//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAdmin.Models.Jira
{
    using System;
    using System.Collections.Generic;
    
    public partial class worklog
    {
        public decimal ID { get; set; }
        public Nullable<decimal> issueid { get; set; }
        public string AUTHOR { get; set; }
        public string grouplevel { get; set; }
        public Nullable<decimal> rolelevel { get; set; }
        public string worklogbody { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public string UPDATEAUTHOR { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<decimal> timeworked { get; set; }
    }
}
